### ISSUE TITLE
Battery status

### ISSUE THREAD

**Issue by gh2311** [guido-visser/vMix-M5Stick-Tally-Light#1]
Show the battery level on the status screen. Doesn't need to be graphical, percentage as text would be fine.

**Comment by guido-visser** [comment]
Can't seem to find any examples on a battery indicator for the M5Stick-C, there is a function for the M5Stack, but that doesn't seem to work with the stick after some testing. I'm afraid that I'll need some help to make this work.

**Comment by guido-visser** [comment]
Glad to say that I found a way to show a battery indicator. It's pushed to the master branch. It will be in v1.3, but before I create a release, I want to look at the other features that are still open. Clone the master branch to start using it :)
