### ISSUE TITLE
Camera number rather than status word display

### ISSUE THREAD

**Issue by fgolman** [guido-visser/vMix-M5Stick-Tally-Light#14]
I'd  like to make a suggestion of just having a big numeral appear rather than the words live, safe, pre. This would allow it to have the camera number appear and be used as an indicator of such. This would be particularly easy to read in vertical orientation.

**Comment by guido-visser** [comment]
I could definitely take a look at this to implement it.

**Comment by guido-visser** [comment]
Implemented this in 2.3.0 😄
