### ISSUE TITLE
Static IP setting

### ISSUE THREAD

**Issue by pawellygan** [guido-visser/vMix-M5Stick-Tally-Light#15]
That would be great to have a static IP setting. I run AP without dhcp server - for tally I set up dhcp on my raspi, but it is a bit slow, which means I have to reboot 2-3 times tally stick to grab an IP. I believe it will be very useful for changing settings too. Most of the users will run always the same private network anyway, having tallys always on the same IPs will only a plus.

**Comment by guido-visser** [comment]
Assigning static IPs to devices is something that needs to be done in the router. The Stick just connects to the wifi AP and gets an IP from the DHCP server. Doesn't look like a problem on this side of the code, but more of a configuration issue in the Router.
