### ISSUE TITLE
Enhancement request - WiFi strength indication

### ISSUE THREAD

**Issue by smadds** [guido-visser/vMix-M5Stick-Tally-Light#20]
Could you add WiFi signal strength to the page showing the connection and IP please? 
(I think the call is WiFi.RSSI())

**Comment by guido-visser** [comment]
Will take a look at this, thanks!

**Comment by kevev** [comment]
Great idea! I second this request.  :)

**Comment by guido-visser** [comment]
I pushed this to the master branch. If you download from this branch, you can use it (Green Code button > Download ZIP). I'll make a new version later, when I have the static IP implemented as well.
