### ISSUE TITLE
Error at the update

### ISSUE THREAD

**Issue by PogoBerlin** [guido-visser/vMix-M5Stick-Tally-Light#23]
HI, I get always the same error:

Arduino: 1.8.13 (Windows 10), Board: "M5Stick-C, Default, 750000, None"

Mehrere Bibliotheken wurden für "WiFi.h" gefunden

a_GLOBAL:12:30: fatal error: k_PLUGINMANAGER.h: No such file or directory

 Benutzt: C:\Users\mreis\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\libraries\WiFi

compilation terminated.

 Nicht benutzt: C:\Program Files (x86)\Arduino\libraries\WiFi

exit status 1

k_PLUGINMANAGER.h: No such file or directory

What to do? I did everything like you discribed in the video
thanks
michael

**Comment by guido-visser** [comment]
I think that the package that you tried to download was somehow corrupted. Can you try downloading the latest release and uploading it again?

**Comment by PogoBerlin** [comment]
tried it with the november and the october release. same error

**Comment by guido-visser** [comment]
When you open up the folder, can you see the `k_PLUGINMANAGER.h` file? The compiler complains that the file doesn't exist. It should...

**Comment by PogoBerlin** [comment]
witch folder? the m5stickc folder?

**Comment by PogoBerlin** [comment]
![Uploading 3BA131A1-90C6-4EF6-B52F-6B45B2B26443.jpeg…]()

**Comment by guido-visser** [comment]
Sorry for the late response (I can't see the picture you posted in your last message). The file can be found at: `src` > `a_GLOBAL` > `k_PLUGINMANAGER.h`. It really looks like you're missing files. Download the package again and extract every file. Then open `a_GLOBAL.ino` and try to upload.

**Comment by PogoBerlin** [comment]
tried it again, and......it worked. 
Thanks so much.

**Comment by guido-visser** [comment]
You're welcome
