### ISSUE TITLE
Stream and Recording indicators are incorrectly aligned on PLUS

### ISSUE THREAD

**Issue by guido-visser** [guido-visser/vMix-M5Stick-Tally-Light#24]
Just as I published 2.4.0, I realized that I didn't check the positions of the REC and STM indicators on the PLUS. Will have to fix this in the future

**Comment by kevev** [comment]
Hi guido-visser. Wondering if you will be able to add this fix soon. We will be using a large set of these tallys very soon. Thank You.

**Comment by guido-visser** [comment]
Hi @kevev, sorry for responding so late. It turns out I already fixed this, but didn't create a build for it. It was residing in the master branch. I created a patch release for this. You can find it here: https://github.com/guido-visser/vMix-M5Stick-Tally-Light/releases/tag/v2.4.1
