### ISSUE TITLE
M5Stick Tally freezes on random tally status even though vmix host is operating normally

### ISSUE THREAD

**Issue by Dirwinc** [guido-visser/vMix-M5Stick-Tally-Light#3]
First off, I really appreciate all the great work you've done here Guido.  Thanks so much!

To preface... I'm guessing my issue is possibly caused by a problem with the wifi network or the vmix machine in my church, because I can't reproduce it on my home wifi network with my personal vmix machine.  But I am able to reproduce it every time when I'm on the church network and the churches vmix machine, to the point where I can't use it during productions.... but I desperately want to!

**Issue Details:**
The M5stick tally works great for 10-20 minutes usually, but sometimes it will freeze in as little as a few seconds or minutes.  But eventually the tally will get stuck/frozen on either "PRE" or "LIVE" or "SAFE", and will not update even when the vmix machine has changed inputs.  And when the M5 A Button is clicked, the Network Screen displays fine, but when clicked again it returns to the same "frozen" tally status screen every time.  The only way to get it to sense the vmix input change is to reboot the M5Stick.  Once rebooted, the tally will work as expected for a short period of time, but always freezes again eventually.  My vMix machine is hardwired to the network, and it does not appear to have any issues.

I'm wondering if it's possible the M5Stick is loosing it's connection to the vmix machine (even though the vmix machine is operating normally), which causes it to always display the last known tally status.  Do you have any thoughts or suggestions on how to troubleshoot this?

Thanks!
Dirwin

**Comment by guido-visser** [comment]
Hi, thanks for the issue. It's hard to narrow down the issue since it's not really reproducable on my end, thus hard to fix the problem. Maybe check your wifi settings on the router of your church and try changing the channels. It looks like a wifi issue and not really an issue with the code.

**Comment by Dirwinc** [comment]
Yep, agreed.  I'm thinking my issue may be some bad EEPROM memory from some other code bases I put on the M5Stick. I found a couple projects to clear out the EEPROM, so I'm going to see if that fixes it.  Thanks
