### ISSUE TITLE
Error firmware upgrade

### ISSUE THREAD

**Issue by AHub88** [guido-visser/vMix-M5Stick-Tally-Light#34]
Hi,

I want to update the firmware from 2.3.0 to 2.4.1.
When I'm uploading it over Arduino it stops on this point:

```
`Writing at 0x00074000... (92 %)
Writing at 0x00078000... (96 %)
Writing at 0x0007c000... (100 %)
Wrote 803120 bytes (446759 compressed) at 0x00010000 in 7.4 seconds (effective 867.3 kbit/s)...
Hash of data verified.
Compressed 3072 bytes to 128...

Writing at 0x00008000... (100 %)
Wrote 3072 bytes (128 compressed) at 0x00008000 in 0.0 seconds (effective 1536.0 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting via RTS pin...`
```

After that, the display of the stick is broken.

**Comment by guido-visser** [comment]
This is exactly what you're supposed to see in the log. The upload is successful. Are you using a PLUS stick?

**Comment by AHub88** [comment]
Yes 
The stick after the upload
![image](https://user-images.githubusercontent.com/99470230/191831725-056925c5-3025-4d86-aa7a-ff4d7ca5433c.jpeg)

**Comment by guido-visser** [comment]
Have you followed Step 2 correctly (changed the `0` to `1` on the first line of `a_GLOBAL.ino`)?

**Comment by AHub88** [comment]
Oh.... Okay....
Thats awkward
