### ISSUE TITLE
Tallys not working anymore

### ISSUE THREAD

**Issue by AHub88** [guido-visser/vMix-M5Stick-Tally-Light#35]
Hi,

we have been using your tally lights for about 1.5 -2 years.
For a few weeks they cannot connect to vMix anymore. 

In the Config everything is correct and when I restart the sticks, they have a connection for a few seconds.
But after that, they try to reconnect, which doesn't work. 
I have already tried several reconnect intervals. From 0-10 seconds. Without success.

Then I updated the stick to the latest firmware.
Unfortunately, the problem persists.
![IMG_0052](https://user-images.githubusercontent.com/99470230/194500042-39ce1efd-2d6f-4b8e-8403-43e7bc2968be.jpg)

Do you have an idea ?

Andi

**Comment by guido-visser** [comment]
Hi Andi, sorry for my late response. 

I have a couple of questions:

Are you using the sticks at the same location? Or are you moving and it just won't connect anymore?
The IP Address on the stick shows 0.0.0.0, which is incorrect. Are you sure the settings are correctly set?

**Comment by guido-visser** [comment]
I double checked and reuploaded the latest version to a PLUS stick. Everything works fine on my side. One thing you should check in vMix:

1. Settings > Web Controller. 
2. Make sure Enabled at the top is checked
3. Make sure that TCP API is also enabled

When this is all configured correctly it should work.

However, that `0.0.0.0` IP Address bothers me a bit. It means that the device isn't getting an IP Address from the router. So it really looks like a network configuration issue on your side. Check your router and look at what devices are connected to it and check that the stick properly connects to your network.

Hope this helps!

**Comment by AHub88** [comment]
Hi,

We have now given the tallys a fixed IP and since then they are working again.

THX!
