### ISSUE TITLE
Req: Multiple inputs to one tally light. 

### ISSUE THREAD

**Issue by kingpyrrhus** [guido-visser/vMix-M5Stick-Tally-Light#4]
Would like to request a feature to allow multiple inputs to be assigned to a single tally light. In our production we use multiviews that use the same camera and also segments where the speaker is talking over prerecorded video. It gets a little confusing when we switch the input and the camera or mic is still on and broadcasting but the light goes off..  

BTW, thank you so much for this solution.

**Comment by guido-visser** [comment]
Thanks for the feature request. The use case is clear. I have an idea on how to implement this. I can't promise that I'll succeed, but I will take a look at it today 😄

**Comment by guido-visser** [comment]
Happy to announce that Multi tally support is now added. Download the [latest release](https://github.com/guido-visser/vMix-M5Stick-Tally-Light/releases/tag/v1.3) to use it 😄
