### ISSUE TITLE
Please advise me on the (M5StickC) phenomenon below.

### ISSUE THREAD

**Issue by julianlee-korea** [guido-visser/vMix-M5Stick-Tally-Light#5]
![Screenshot 2020-08-05 at 18 12 18](https://user-images.githubusercontent.com/68336984/89398253-d5572a80-d74b-11ea-8813-bdc55b1860a3.jpg)
![Screenshot 2020-08-05 at 18 11 54](https://user-images.githubusercontent.com/68336984/89398258-d5efc100-d74b-11ea-9ff4-87ab7742fb12.jpg)
![Screenshot 2020-08-05 at 18 11 16](https://user-images.githubusercontent.com/68336984/89398261-d6885780-d74b-11ea-9ada-dcd61480a250.jpg)
![Screenshot 2020-08-05 at 18 02 09](https://user-images.githubusercontent.com/68336984/89398262-d6885780-d74b-11ea-9eec-fb9ce05e3fd4.jpg)

Guido's M5StickC software downloads well onto M5StickC.
But M5StickC's message is "Connecting to vmix ... And Connected to vmix!" it repeats.
The vmix version used is 4K-23.0.60 .

julianlee

**Comment by guido-visser** [comment]
Hi Julian,

I'm sorry for the confusion. I should've changed the comments around the variables in the pictures you sent (I just updated it). You shouldn't change any code. Including those variables. You can change them in the web UI. I'll make a configuration tutorial today and walk you through it. 

Please change back the variables to what they were. The code subscribes to the TALLY subscription of the [TCP API of vMix](https://www.vmix.com/help23/index.htm?TCPAPI.html). The TCP port of vMix is fixed at `8099` and you shouldn't change that. 

If you follow the video tutorial of uploading the code the the stick, you're ready for the configuration tutorial that I'll make today.

P.s. I recommend editing your previous message and delete the picture with the wifi credentials. People don't need to know what those are.

**Comment by guido-visser** [comment]
While recording the tutorial, I stumbled upon annoying problems. I fixed those in the latest release, but now I don't have enough time to record a tutorial now. Hopefully I can do it soon.

**Comment by guido-visser** [comment]
I just updated the documentation. I hope it's clear enough for you to make it work in your environment. Please let me know your progress, so I can update or close this issue.

**Comment by guido-visser** [comment]
Since you've posted on the vMix forums that it now works, I'll close this issue :)
