### ISSUE TITLE
Feature Request - re SAFE in webserver mode

### ISSUE THREAD

**Issue by nottooloud** [guido-visser/vMix-M5Stick-Tally-Light#7]
Off site, just loaded 1.3. Delighted to see that it held my earlier settings. It's in webserver mode, though, not connected to vMix, and it says SAFE. Maybe it should say offline or server mode or something else to indicate that it's not synced.

**Comment by Dirwinc** [comment]
I noticed this too.   I like the idea of saying something else on the screen when the connection is lost.

**Comment by guido-visser** [comment]
I'm back from my week off internet. Will look at this issue sson

**Comment by guido-visser** [comment]
Just fixed this in v1.4.

Check the new features on the [release page](https://github.com/guido-visser/vMix-M5Stick-Tally-Light/releases/tag/v1.4)
